version: "3.3"

services:
  simulador:
    container_name: simulador
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - "./frontend:/frontend"
      - "./frontend/node_modules:/frontend/node_modules"
